services:
  app:
    build: ./backend
    container_name: agileContainer
    ports:
      - "8080:8080"
    env_file:
      - .env                         
    environment:
      - DB_URL=jdbc:oracle:thin:@reacttodo2p9ml_medium?TNS_ADMIN=/app/wallet
      - DB_USERNAME=MANAGER
      - DB_PASSWORD=MxTodo#2026Pass9
      - TELEGRAM_BOT_TOKEN=8336070482:AAE5hiBc8D2m1UA38YGjFX-wgua235RIRzM
    volumes:
      - ./backend/wallet:/app/wallet
    restart: unless-stopped