services:
  app:
    build: ./backend
    container_name: agileContainer
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    environment:
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    volumes:
      - ./backend/wallet:/app/wallet
    restart: unless-stopped
