-- Migrate existing TASK_EMBEDDINGS to native Oracle VECTOR (23ai+ only).
-- Run as MANAGER after 00_check_vector_support.sql succeeds.

ALTER TABLE MANAGER.TASK_EMBEDDINGS ADD (
    EMBEDDING_VEC VECTOR(768, FLOAT64)
);

-- Backfill from legacy JSON CLOB where present (optional; re-index via API is preferred).
-- UPDATE MANAGER.TASK_EMBEDDINGS
-- SET EMBEDDING_VEC = TO_VECTOR(EMBEDDING, 768, FLOAT64)
-- WHERE EMBEDDING IS NOT NULL AND EMBEDDING_VEC IS NULL;

CREATE VECTOR INDEX MANAGER.TASK_EMBEDDINGS_VEC_IDX
ON MANAGER.TASK_EMBEDDINGS (EMBEDDING_VEC)
ORGANIZATION NEIGHBOR PARTITIONS
WITH TARGET ACCURACY 95
DISTANCE COSINE;
